apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: webapp-ingress
spec:
  rules:
  - host: webapp.ingress.example
    http:
      paths:
      - path: /webapp01
        backend:
          serviceName: webapp01-svc
          servicePort: 80
      - path: /webapp02
        backend:
          serviceName: webapp02-svc
          servicePort: 80
      - backend:
          serviceName: webapp03-svc
          servicePort: 80
